language: node_js
node_js:
    - "10"
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
install:
    - npm install
    - npm install -g @vue/cli
    - npm install -g @vue/cli-service-global
script:
    - npm run build
cache:
    directories:
       - $HOME/.npm
notifications:
    email: false
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: dist
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    repo: andreaschrist27/andreaschrist27.github.io
    keep-history: true
    target-branch: master
    on:
        branch: master